(function( $ ) {
	'use strict';

	/**
	 * All of the code for your admin-facing JavaScript source
	 * should reside in this file.
	 *
	 * Note: It has been assumed you will write jQuery code here, so the
	 * $ function reference has been prepared for usage within the scope
	 * of this function.
	 *
	 * This enables you to define handlers, for when the DOM is ready:
	 *
	 * $(function() {
	 *
	 * });
	 *
	 * When the window is loaded:
	 *
	 * $( window ).load(function() {
	 *
	 * });
	 *
	 * ...and/or other possibilities.
	 *
	 * Ideally, it is not considered best practise to attach more than a
	 * single DOM-ready or window-load handler for a particular page.
	 * Although scripts in the WordPress core, Plugins and Themes may be
	 * practising this, we should strive to set a better example in our own work.
	 */

	function update_slide_format_meta_boxes() {		
		var slide_format = $('#foyer_slide_format input[name=slide_format]:checked').val();
		$('.postbox[id*=foyer_slide_format_]').hide();
		$('#foyer_slide_format_'+slide_format).show();		
	}


	 $(function() {
		 /* DOM is ready */

		 $('.foyer_slides_editor_form_action_remove').unbind('click').click(function(e) {

				if (confirm(foyer_slides_editor_defaults.confirm_remove_message)) {

					var data = {
						'action': 'foyer_slides_editor_remove_slide',
						'channel_id': $(e.currentTarget).parents('table').data('channel-id'),
						'slide_key': $(e.currentTarget).parents('tr').data('slide-key'),
						'nonce': foyer_slides_editor_security.nonce,
					};

					$.post(ajaxurl, data, function(response) {
						if (response != '') {
							$('*[data-slide-key="'+response+'"]').remove();
						}
					});

				}

				return false;


		 });
		 
		 update_slide_format_meta_boxes();
		 $('#foyer_slide_format input[name=slide_format]').on('change', function() {
			update_slide_format_meta_boxes();
		 });

	});


	jQuery(function() {
	  var set_to_post_id, wp_media_post_id;
	  if (wp.media) {
	    wp_media_post_id = wp.media.model.settings.post.id;
	    set_to_post_id = foyer_slide_format_default.photo;
	    jQuery('#upload_image_button').on('click', function(event) {
	      var file_frame;
	      event.preventDefault();
	      if (file_frame) {
	        file_frame.uploader.uploader.param('post_id', set_to_post_id);
	        file_frame.open();
	        return;
	      } else {
	        wp.media.model.settings.post.id = set_to_post_id;
	      }
	      file_frame = wp.media.frames.file_frame = wp.media({
	        title: foyer_slide_format_default.text_select_photo,
	        button: {
	          text: foyer_slide_format_default.text_use_photo
	        },
	        multiple: false
	      });
	      file_frame.on('select', function() {
	        var attachment;
	        attachment = file_frame.state().get('selection').first().toJSON();
	        jQuery('#image-preview').attr('src', attachment.url).css('width', 'auto');
	        jQuery('#image_attachment_id').val(attachment.id);
	        wp.media.model.settings.post.id = wp_media_post_id;
	      });
	      file_frame.open();
	    });
	    return jQuery('a.add_media').on('click', function() {
	      wp.media.model.settings.post.id = wp_media_post_id;
	    });
	  }
	});

// ---
// generated by coffee-script 1.9.2



})( jQuery );
